Design/refractor directories
InternetEnemies/combatcritters-maui pull request #13
Opened 2024-10-03 06:17 UTC by idafum

Restructured code to use MVVM design pattern and enabled support for data binding.

2024-10-03 14:39 UTC, VanJackal requested changes
A few bits of commented out code, otherwise looks good

2024-10-03 14:39 UTC, VanJackal commented on Models/Card.cs
this will need to be moved to the wrapper later, fine to stay here though

2024-10-03 14:39 UTC, VanJackal commented on Pages/ProfilePage.xaml
> +        </ContentView> -->
dead code

2024-10-03 14:39 UTC, VanJackal commented on Pages/ProfilePage.xaml.cs
> +            //BindingContext = new ProfilePageViewModel();
dead code

2024-10-04 02:54 UTC, idafum reviewed
Reviewed

2024-10-04 02:56 UTC, idafum commented on Models/Card.cs
Okay, I wonder how it would be implemented in the wrapper?

2024-10-04 02:57 UTC, merged